package vermouth


// import (
// 	"fmt"
// 	"os"
// 	"text/template"
// )

// const tmpl = `// Code generated by go generate; DO NOT EDIT.
// package main

// func ConvertSourceToDestination(src Source) Destination {
// 	return Destination{
// 		Name:  src.Name,
// 		Age:   src.Age,
// 		Email: src.Email,
// 	}
// }
// `